name: Merge to Main from Develop

on:
  push:
    branches:
      - develop

jobs:
  create-pr-to-main-from-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Generate PR body
        env:
          PULL_REQUESTS: ${{ toJson(github.event.commits) }}
        run: |
          echo "$PULL_REQUESTS" > commits.json
          ruby -rerb -rjson -e "
            require 'erb'
            require 'json'
            require 'ostruct'
            commits = JSON.parse(File.read('commits.json'))
            pull_requests = commits.map { |commit| OpenStruct.new(to_checklist_item: \"- [ ] #{commit['message']}\") }
            template = ERB.new(File.read('.github/git-pr-release.develop-to-main.template'))
            File.write('pr_body.txt', template.result_with_hash(pull_requests: pull_requests))
          "

      - name: Read PR body into environment variable
        id: read_pr_body
        run: |
          pr_body=$(<pr_body.txt)
          echo "::set-output name=pr_body::$pr_body"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge changes from develop to main
          branch: merge/develop-to-main
          title: '【Auto】Merge changes from develop to main'
          body: ${{ steps.read_pr_body.outputs.pr_body }}
          base: main
          head: develop
